### PR TITLE
Remove dep exclusions

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Review by whyoleg — APPROVED** [review]
need to wait for [pipeline](https://github.com/rsocket/rsocket-kotlin/actions/runs/310116325) to finish for publication of version with fix.
but it should work

**Comment by whyoleg** [comment]
@yschimke can you restart travis build?

**Comment by yschimke** [comment]
done https://travis-ci.org/github/rsocket/rsocket-cli/builds/736291822

**Comment by whyoleg** [comment]
Looks like it uses old snapshot: `0.10.0-SNAPSHOT:20201004.205048-10` and not `20201016.**`

**Comment by yschimke** [comment]
Maybe 24 hours. I'll look after work

**Pull request merged**
